{% set version = "1.04" %}

package:
  name: lra
  version: {{ version }}

source:
  url: https://github.com/ChaissonLab/LRA/archive/V1.0.5.tar.gz
  sha256: 2ac0de3c5731350ea65d3dcbd8b9eb31f5079fbb6faabe859399c17ede33e5c2



build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib
    - pthreads
  run:
    - zlib
    - pthreads

test:
  commands:
    - lra | grep 'Usage'

about:
  home: https://github.com/ChaissonLab/LRA
  license: USC-RL v1.0
  license_file: LICENSE.txt
  summary: 'Long read aligner for sequences and contigs'
