{% set version = "3.0.4" %}
{% set name = "vamos" %}

package:
  name: vamos
  version: {{ version }}

source:
  url: https://github.com/ChaissonLab/vamos/archive/refs/tags/vamos-v{{ version }}.tar.gz
  sha256: fdd2cac40276d49663ca9d025e2dffa98819b34b84db09896b9f51e9f3af1981
  patches:
    - vamos-aarch64.patch  # [arm64 or aarch64]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - make
    - cmake <3.29
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - htslib
    - boost-cpp
  run:
    - htslib
    
test:
  commands:
    - vamos | grep 'Usage'

about:
  home: "https://github.com/ChaissonLab/vamos"
  license: "GPL-2.0-only"
  license_family: GPL
  license_file: "LICENSE.txt"
  summary: 'VNTR annotation using efficient motif selection.'
  dev_url: "https://github.com/ChaissonLab/vamos"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
