{% set version = "3.0.3" %}
{% set name = "vamos" %}

package:
  name: vamos
  version: {{ version }}

source:
  url: https://github.com/ChaissonLab/vamos/archive/refs/tags/vamos-v{{ version }}.tar.gz
  sha256: c9089a07fd0aeb38ec67e69a8aa5b8de5e66b9438bab21eafb1ca37b9d9a28df
  patches:
    - vamos-aarch64.patch  # [arm64 or aarch64]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - make
    - cmake <3.29
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - htslib
    - boost-cpp
  run:
    - htslib
    
test:
  commands:
    - vamos | grep 'Usage'

about:
  home: "https://github.com/ChaissonLab/vamos"
  license: "GPL-2.0-only"
  license_family: GPL
  license_file: "LICENSE.txt"
  summary: 'VNTR annotation using efficient motif selection.'
  dev_url: "https://github.com/ChaissonLab/vamos"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
