{% set version = "1.0" %}

package:
  name: ctyper 
  version: {{ version }}

source:
  url: https://github.com/ChaissonLab/Ctyper/archive/refs/tags/v{{version}}.tar.gz 
  sha256: 55ea1f5a46149e5c5da1e1c2ebe4159a175d8af649ee579174fe97e8da4b91c0
  patches:
    - ctyper-aarch64.patch # [linux and aarch64]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('ctyper', max_pin='x.x') }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - zlib 1.2.*    

  host:
    - zlib
    - htslib
    - boost
    - zlib 1.2.*    
    - eigen
  run:
    - htslib
    - zlib 1.2.*
    - eigen
    
test:
  commands:
    - ctyper | grep 'Usage'

about:
  home: https://github.com/ChaissonLab/Ctyper
  license: USC-RL v1.0
  license_file: LICENSE.txt
  summary: 'Genotyping sequence-resolved copy-number variation using pangenomes'

extra:
  additional-platforms:
    - linux-aarch64
