{% set name = "ctyper" %}
{% set version = "1.0.4" %}

# IMPORTANT: For bioconda::htslib 1.21 (built with a newer gcc) to be used,
# build this recipe with channel ordering as follows:
# conda build recipes/ctyper/ -c bioconda -c conda-forge


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ChaissonLab/Ctyper/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bee5b6dd1d13e5164141be7f87dd1a2c1ce2b3169c876bcdfadad68a14176d86 

build:
  number: 0
  skip: True [osx]
  run_exports:
    - {{ pin_subpackage('ctyper', max_pin='x') }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - bioconda::htslib >=1.21  # Pin to version 1.21 (this package must come from bioconda)
    - boost-cpp
    - eigen
  run:
    - bioconda::htslib >=1.21  # Use the same pinning for runtime
    - eigen

test:
  commands:
    - ctyper -h | grep 'Usage'

about:
  home: https://github.com/ChaissonLab/Ctyper
  license: "USC-RL v1.0"
  license_file: License.txt
  summary: 'Genotyping sequence-resolved copy-number variation using pangenomes.'
  dev_url: https://github.com/ChaissonLab/Ctyper

extra:
  additional-platforms:
    - linux-aarch64

