{% set version = "2.1.1" %}
{% set sha256 = "ba7c2548d95558459d60f640faa31707bff5bf382a66797809fea52a0197a7a3" %}

package:
  name: canu
  version: '{{version}}'

source:
  url: https://github.com/marbl/canu/archive/v{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  number: 0
  # This should actually work, but it explicitly checks for gcc
  skip: True  # [osx]

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
  host:
    - gnuplot >=5.2
  run:
    - perl
    - perl-filesys-df
    - openjdk
    - gnuplot >=5.2

test:
  commands:
    - canu --version

about:
  home: http://canu.readthedocs.org/
  license: GPLv2 and others
  license_file: README.licenses
  license_family: GPL
  summary: Canu is a fork of the Celera Assembler designed for high-noise single-molecule
    sequencing.
  dev_url: https://github.com/marbl/canu

extra:
  identifiers:
    - usegalaxy-eu:canu
